---
name: "Release Tagged Version"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Release Tagged Version"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false